### ISSUE TITLE
Przenosiny CDN MathJax

### ISSUE THREAD

**Issue by marcmos** [zmora-agh/zmora-ui#105]
Ostatnio zaczął się pojawiać taki komunikat w konsoli: `WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.`

Jest to dobry pretekst, żeby trzymać biblioteki razem z projektem (i być z powrotem offline-first, bo to jest bodajże jedyna zależność pobierana z internetu).

**Comment by mflis** [comment]
też to zauważyłem. Na szybko można to załatać taką podmianą
```
      <MathJax.Context script="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML">
        <ReactMarkdown source={text} renderers={{ code: Code, code_block: CodeBlock }} />
      </MathJax.Context>
 ```

Wersji ofline nie próbowałem jeszcze wdrożyć

**Comment by maxmati** [comment]
Jeżeli chodzi o wersje offline to mathjax ma wspierać webpacka od wersji 3 ale nie wiem kiedy ma ona wyjść
