### ISSUE TITLE
Lista contestów ma wyglądać 1 do 1 jak w inboxie (zwijanie/rozwijanie)

### ISSUE THREAD

**Issue by oszust002** [zmora-agh/zmora-ui#120]
Wygląd schowany:
![hidden](https://cloud.githubusercontent.com/assets/9934486/25963113/7d945792-3680-11e7-8d0f-1794b9660a60.png)

Wygląd rozwinięty:
![expanded](https://cloud.githubusercontent.com/assets/9934486/25963114/7d954558-3680-11e7-88df-37dda13ec5d6.png)

**Comment by marcmos** [comment]
Nie ma sensu się tym zajmować, przynajmniej do momentu ostatecznej decyzji, jak będzie wyglądała część administracyjna zarządzania contestami.
