### ISSUE TITLE
Przy odświeżeniu strony na zakładce results (jestem ownerem contestu) zakładka znika

### ISSUE THREAD

**Issue by oszust002** [zmora-agh/zmora-ui#151]
W konsoli dostaję przy tym błąd że zakładka nie istnieje (prawdopodobnie dlatego że indeks się ustawił na właśnie tą zakładkę)
![image](https://cloud.githubusercontent.com/assets/9934486/26527565/bf4a9e58-4396-11e7-92a3-e61898e552c5.png)

**Comment by marcmos** [comment]
Przeklejam moje wnioski z #158:
W przypadku wejścia bezpośrednio z linku na rezultatu problemów zakładka "Results" nie jest widoczna i w konsoli pojawia się błąd. Po kliknięciu na dowolną inną zakładka staje się widoczna.
Problem najwyraźniej związany jest z tym, że komponent z rezultatami chce się wyświetlić szybciej niż może, tj. zanim pojawi się odpowiedź od serwera, że jesteśmy właścicielami contestu.
