### ISSUE TITLE
Ukrycie nie-funkcjonalnych elementów UI

### ISSUE THREAD

**Issue by marcmos** [zmora-agh/zmora-ui#159]
- [x] wycięcie grafiki obciążenia klastra ze strony głównej
- [x] ukrycie wyszukiwarki
- [x] ukrycie streamów wydarzeń w wysuwanym menu #82 
- [x] wycięcie niewidzialnej podstrony (contest) z breadcrumbs
- [x] wycięcie bądź uzupełnienie strony „About Zmora”
- [x] wycięcie bądź uzupełnienie zakładki „Questions”
- [x] ukrycie przycisku generującego PDF
- [x] ukrycie „soft deadline”
- [x] ukrycie liczby punktów „base points”
Do powyższych trzeba będzie założyć osobne issues.

**Comment by maxmati** [comment]
Zrobiłem PR który zawiera to wszystko żeby tam po kolei robić (https://github.com/zmora-agh/zmora-ui/pull/165). Dlatego zamykam.
