### ISSUE TITLE
Obsługa deadline/błędów przy wysyłaniu submitu

### ISSUE THREAD

**Issue by marcmos** [zmora-agh/zmora-ui#193]
Uploader nie implementuje obsługi błędów. Funkcjonalność jest istotna ze względu na obsługę deadline'ów (zmora-agh/zmora-server-rails#46). Dobrze byłoby wykorzystać aktualny czas serwera do wyłączenia części UI, jednak nie jestem przekonany, jak miałoby to wyglądać. Czas w przeglądarce nigdy nie będzie identyczny z czasem serwera, a nie chcemy, żeby ktoś był poszkodowany z powodu programowego wyłączenia uploadu (czyli gdy zapytanie za pomocą `curl` ma szansę udać się).

**Comment by maxmati** [comment]
Czas jest synchronizowany z serwerem więc powinien się w miarę zgadzać. Można przesunąć po stronie UI, deadline o 10-20 sekund i już nie będzie takiej sytuacji jak opisujesz.

**Comment by marcmos** [comment]
W momencie zablokowania problemu serwer wysyła `403 Forbdden`.

**Comment by maxmati** [comment]
fixed with #224
