### ISSUE TITLE
Lista pytań i odpowiedzi na stronie zadania

### ISSUE THREAD

**Issue by korrix** [zmora-agh/zmora-ui#27]
Wygląd powinien prrzypominać komentarze na google+ (mniej więcej, nie trzeba nam dokładnej kopii)

**Comment by mflis** [comment]
@korrix, czy uwzględniamy możliwość, że studenci odpowiadają nawzajem na swoje pytania, czy jedynie serwujemy statyczną treść, bo wszystko musi najpierw zostać zatwierdzone przez prowadzącego?

**Comment by korrix** [comment]
@mflis No nie statyczną, bo dynamiczną :) ale:
1. Na pytania odpowiadają tylko prowadzący
2. Pytanie wyświetla się dopiero kiedy posiada przynajmniej jedną odpowiedź (co jest równoważne z akceptacją pytania)
3. Prowadzący może zmienić treść pytania przed udzieleniem odpowiedzi na nie.

**Comment by mflis** [comment]
ok, to upraszcza sprawę, bo nie trzeba się bawić w przyciski "dodaj odpowiedź" i logikę z tym związaną(przynajmniej od tej części portalu[dla studenta]).

@korrix Przy okazji pasuje uszczegółowić:  "Wygląd powinien przypominać komentarze na google+ ", bo jest tu kilka elementów (wskaż które miałeś na myśli):

1. Pytanie jest w postaci  kafelka w stylu [material-ui card](https://material-ui-1dab0.firebaseapp.com/component-demos/cards) z listą odpowiedzi rozwijaną po kliknięciu w ikonę komentarza
![image](https://cloud.githubusercontent.com/assets/15031715/25724917/ebcc87ec-311d-11e7-85b8-c43da67a78ea.png)

2. Kafelki dynamicznie wypełniają całą dostępną przestrzeń na ekranie
// może być dosyć trudne, o ile nie znajdę na to gotowego komponentu
![image](https://cloud.githubusercontent.com/assets/15031715/25725002/56235300-311e-11e7-93af-a4109985e790.png)

3. Czy chodziło ci po prostu o ten element  wraz z treścią  pytania
![image](https://cloud.githubusercontent.com/assets/15031715/25725520/aa8fd786-3120-11e7-947e-295999d55c82.png)

**Comment by korrix** [comment]
Coś w stylu karty wypełniającej cały ekran (czyli jedna karta jedno pytanie, karty tworzą jedną kolumnę). Pytanie odpowiednio większym fontem, odpowiedzi tak jak na pierwszym przykładzie. Oczywiście żadnych obrazków ani dodatkowych komponentów w karcie :)
