### ISSUE TITLE
Uploader plików

### ISSUE THREAD

**Issue by korrix** [zmora-agh/zmora-ui#28]
- Na stronie listy submitów powinien być jakiś estetyczny przycisk, po kliknięciu którego pojawia się okienko wyboru pliku

- na belce głównej powinien być drugi przycisk/ikonka (między ikonkami czasu serwera a ikonką rozwijania prawego panelu). Po jego kliknięciu powinien pokazywać się modal zawierający select'a z zadaniami i przycisk otwierający okienko wyboru plików. Domyślną wartością selecta powinno być zadanie na stronie którego aktualnie jesteśmy / pusta wartość jeśli jesteśmy na jakiejś innej stronie.

**Comment by oszust002** [comment]
W pojedyńczym submicie zamiast przycisków edit/download i checksumy powininna być ikona do rozwijania, dopiero tam ma być lista plików gdzie jest nazwa pliku, checksum, przycisk do edycji i ściągnięcia

**Comment by marcmos** [comment]
@korrix, proponuję podstawowy modal z powrzucanymi elementami. `ZMR_1` to jest shortcode problemu, pod spodem pełna nazwa. Pasek u góry pokazuje postęp wysyłania plików.

![Uploader](https://cloud.githubusercontent.com/assets/63678/26003248/7187b022-3732-11e7-9038-9cf2988377ce.png)

![Uploader – problem select](https://cloud.githubusercontent.com/assets/63678/26003654/9b08d6fa-3733-11e7-8390-6c08cdfe0fca.png)


@RandyTheGuineaPig, przepinam issue na siebie.
