### ISSUE TITLE
Wygląd strony głównej

### ISSUE THREAD

**Issue by marcmos** [zmora-agh/zmora-ui#29]
Dwa komponenty do zasilenia:
* `InfoPanel`
* `NewsPanel`

**Comment by korrix** [comment]
Tutaj jest kwestia tego, że nie chcemy reimplementować funkcjonalności wordpressa. Moja oryginalna propozycja była taka, żeby część strony głównej z newsami była po prostu serwowanym statycznym plikiem markdowna. Odpada wtedy kwestia archiwizowania tego.

**Comment by maxmati** [comment]
@korrix ja bym zrobił pojedynczy wpis markdowna ale edytowalny przez panel admina co by było wygodniej

**Comment by marcskow** [comment]
Wydaje mi się, że archiwizowanie newsów jest dobre, ale możemy od tego odejść.
Do tego strona główna może stracić na tym wizualnie.

Czyli co, NewsPanel przerobić na pojedynczy wpis markdowna? Czy markdown w naszym projekcie jest już gdzieś wykorzystywany?

**Comment by mflis** [comment]
W ProblemView jest zaimplementowany. Ale będzie jeszcze wyciągany do osobnego komponentu i stylowanie trzeba spójne dorobić

**Comment by korrix** [comment]
@marcskow Na razie jeszcze poczekaj - jutro siądę do photoshopa i zaprojektuję stronę główną tak jak (moim zdaniem) powinna wyglądać. Bez tego chyba będzie ciężko się dogadać :)
