### ISSUE TITLE
Wygląd strony „lista problemów”

### ISSUE THREAD

**Issue by marcmos** [zmora-agh/zmora-ui#40]
Proponowany wygląd:
Paper z rozwijanymi kategoriami zadań (jednak domyślnie wszystkie kategorie powinny być rozwinięte)
W każdej kategorii tabelka:
shortcode | tytuł zadania | kod sposobu oceniania | aktualna ilość punktów | termin | przyciski - "submit" i "pdf"

**Comment by maxmati** [comment]
Proponuje wykorzystać elementy z contests page tylko ze zmienionym headerem i contentem .

**Comment by marcskow** [comment]
Podoba mi się przedstawiony tutaj pomysł wyglądu +1
