### ISSUE TITLE
Strona z podsumowaniem contestu

### ISSUE THREAD

**Issue by marcmos** [zmora-agh/zmora-ui#52]
Przykładowy adres strony: `/contests/2`.

**Comment by mflis** [comment]
Może więcej szczegów jak ma to wyglądać?

**Comment by maxmati** [comment]
Wydaje mi się że problemem jest że nie bardzo ktoś wie co to ma być. Może @korrix

**Comment by marcmos** [comment]
Co będzie wyświetlane pod `/contests/2`, a co pod `/contests/2/problems`?
