### ISSUE TITLE
Formularz rejestracji nie umożliwia rejestracji

### ISSUE THREAD

**Issue by rpieja** [zmora-agh/zmora-ui#88]
Aktywowanie przycisku rejestracji nie jest możliwe, niezależnie od podanych danych w formularzu.

![selection_005](https://cloud.githubusercontent.com/assets/15822127/24832148/678535a2-1ca9-11e7-9352-9aee8f493e63.png)

**Comment by maxmati** [comment]
Bez kropki też nie działa:
![2017-04-08-223324_795x410_scrot](https://cloud.githubusercontent.com/assets/509560/24832245/740f2998-1cab-11e7-86a6-046be1191922.png)


To jest po prostu brak informacji o nie spełnieniu patternu.
